package net.foound.util;

public class Constants
{
	// model.service
	public static final String TEXT_USER_IS_NOT_LOGGED_IN = "USER_IS_NOT_LOGGED_IN";
	public static final String TEXT_INVALID_USER_CREDENTIALS_FORMAT = "INVALID_USER_CREDENTIALS_FORMAT";
	public static final String TEXT_USER_CREDENTIALS_NOT_FOUND = "USER_CREDENTIALS_NOT_FOUND";
	public static final String TEXT_YOU_DO_NOT_HAVE_PERMISSION = "YOU_DO_NOT_HAVE_PERMISSION";
	public static final String TEXT_UNAUTHORIZED_USER = "UNAUTHORIZED_USER";
	public static final String TEXT_USER_NOT_FOUND = "USER_NOT_FOUND";
	public static final String TEXT_INVALID_USER_PASSWORD = "INVALID_USER_PASSWORD";
	public static final String TEXT_CLIENT_NOT_FOUND = "CLIENT_NOT_FOUND";
	public static final String TEXT_USER_DOES_NOT_EXIST = "USER_DOES_NOT_EXIST";
	public static final String TEXT_USER_IS_NOT_A_CLIENT = "USER_IS_NOT_A_CLIENT";
	public static final String TEXT_CLIENT_DOES_NOT_EXIST = "CLIENT_DOES_NOT_EXIST";
	public static final String TEXT_PROMOTION_DOES_NOT_EXIST = "PROMOTION_DOES_NOT_EXIST";
	public static final String TEXT_ESTABLISHMENT_MUST_BE_ACTIVE = "ESTABLISHMENT_MUST_BE_ACTIVE";
	public static final String TEXT_CLIENT_MUST_BE_ACTIVE = "CLIENT_MUST_BE_ACTIVE";
	public static final String TEXT_PROMOTION_MUST_BE_ACTIVE = "PROMOTION_MUST_BE_ACTIVE";
	public static final String TEXT_SCORE_CAN_NOT_BE_NEGATIVE = "SCORE_CAN_NOT_BE_NEGATIVE";
	public static final String TEXT_CLIENT_ID_MUST_BE_NULL = "CLIENT_ID_MUST_BE_NULL";
	public static final String TEXT_CLIENT_EMAIL_IS_ALREADY_IN_USE = "CLIENT_EMAIL_IS_ALREADY_IN_USE";
	public static final String TEXT_CLIENT_ID_MUST_NOT_BE_NULL = "CLIENT_ID_MUST_NOT_BE_NULL";
	public static final String TEXT_CLIENT_USER_IS_ALREADY_IN_USE = "CLIENT_USER_IS_ALREADY_IN_USE";
	public static final String TEXT_CLIENT_MUST_NOT_BE_NULL = "CLIENT_MUST_NOT_BE_NULL";
	public static final String TEXT_CLIENT_USER_MUST_NOT_BE_NULL = "CLIENT_USER_MUST_NOT_BE_NULL";
	public static final String TEXT_CLIENT_NAME_MUST_NOT_BE_EMPTY = "CLIENT_NAME_MUST_NOT_BE_EMPTY";
	public static final String TEXT_CLIENT_NAME_MUST_NOT_BE_BIGGER_THAN_120_CHARACTERS = "CLIENT_NAME_MUST_NOT_BE_BIGGER_THAN_120_CHARACTERS";
	public static final String TEXT_CLIENT_BIRTHDAY_MUST_NOT_BE_NULL = "CLIENT_BIRTHDAY_MUST_NOT_BE_NULL";
	public static final String TEXT_CLIENT_BIRTHDAY_IS_INVALID = "CLIENT_BIRTHDAY_IS_INVALID";
	public static final String TEXT_CLIENT_EMAIL_MUST_NOT_BE_EMPTY = "CLIENT_EMAIL_MUST_NOT_BE_EMPTY";
	public static final String TEXT_CLIENT_EMAIL_MUST_NOT_BE_BIGGER_THAN_320_CHARACTERS = "CLIENT_EMAIL_MUST_NOT_BE_BIGGER_THAN_320_CHARACTERS";
	public static final String TEXT_CLIENT_EMAIL_IS_INVALID = "CLIENT_EMAIL_IS_INVALID";
	public static final String TEXT_CLIENT_SEX_MUST_NOT_BE_NULL = "CLIENT_SEX_MUST_NOT_BE_NULL";
	public static final String TEXT_CLIENT_SEX_IS_INVALID = "CLIENT_SEX_IS_INVALID";
	public static final String TEXT_ESTABLISHMENT_NOT_FOUND = "ESTABLISHMENT_NOT_FOUND";
	public static final String TEXT_AVATAR_MIME_TYPE_NOT_SUPPORTED = "AVATAR_MIME_TYPE_NOT_SUPPORTED";
	public static final String TEXT_ESTABLISHMENT_ID_MUST_BE_NULL = "ESTABLISHMENT_ID_MUST_BE_NULL";
	public static final String TEXT_ESTABLISHMENT_NAME_ADDRESS_LATITUDE_LONGITUDE_IS_ALREADY_IN_USE = "ESTABLISHMENT_NAME_ADDRESS_LATITUDE_LONGITUDE_IS_ALREADY_IN_USE";
	public static final String TEXT_ESTABLISHMENT_ID_MUST_NOT_BE_NULL = "ESTABLISHMENT_ID_MUST_NOT_BE_NULL";
	public static final String TEXT_ESTABLISHMENT_DOES_NOT_EXIST = "ESTABLISHMENT_DOES_NOT_EXIST";
	public static final String TEXT_ESTABLISHMENT_USER_IS_ALREADY_IN_USE = "ESTABLISHMENT_USER_IS_ALREADY_IN_USE";
	public static final String TEXT_ESTABLISHMENT_MUST_NOT_BE_NULL = "ESTABLISHMENT_MUST_NOT_BE_NULL";
	public static final String TEXT_ESTABLISHMENT_USER_MUST_NOT_BE_NULL = "ESTABLISHMENT_USER_MUST_NOT_BE_NULL";
	public static final String TEXT_ESTABLISHMENT_NAME_MUST_NOT_BE_EMPTY = "ESTABLISHMENT_NAME_MUST_NOT_BE_EMPTY";
	public static final String TEXT_ESTABLISHMENT_NAME_MUST_NOT_BE_BIGGER_THAN_120_CHARACTERS = "ESTABLISHMENT_NAME_MUST_NOT_BE_BIGGER_THAN_120_CHARACTERS";
	public static final String TEXT_ESTABLISHMENT_ADDRESS_MUST_NOT_BE_EMPTY = "ESTABLISHMENT_ADDRESS_MUST_NOT_BE_EMPTY";
	public static final String TEXT_ESTABLISHMENT_ADDRESS_MUST_NOT_BE_BIGGER_THAN_120_CHARACTERS = "ESTABLISHMENT_ADDRESS_MUST_NOT_BE_BIGGER_THAN_120_CHARACTERS";
	public static final String TEXT_ESTABLISHMENT_ABOUT_MUST_NOT_BE_EMPTY = "ESTABLISHMENT_ABOUT_MUST_NOT_BE_EMPTY";
	public static final String TEXT_ESTABLISHMENT_ABOUT_MUST_NOT_BE_BIGGER_THAN_255_CHARACTERS = "ESTABLISHMENT_ABOUT_MUST_NOT_BE_BIGGER_THAN_255_CHARACTERS";
	public static final String TEXT_ESTABLISHMENT_LATITUDE_MUST_NOT_BE_NULL = "ESTABLISHMENT_LATITUDE_MUST_NOT_BE_NULL";
	public static final String TEXT_ESTABLISHMENT_LATITUDE_IS_INVALID = "ESTABLISHMENT_LATITUDE_IS_INVALID";
	public static final String TEXT_ESTABLISHMENT_LONGITUDE_MUST_NOT_BE_NULL = "ESTABLISHMENT_LONGITUDE_MUST_NOT_BE_NULL";
	public static final String TEXT_ESTABLISHMENT_LONGITUDE_IS_INVALID = "ESTABLISHMENT_LONGITUDE_IS_INVALID";
	public static final String TEXT_PROMOTION_CREATION_MUST_BE_NULL = "PROMOTION_CREATION_MUST_BE_NULL";
	public static final String TEXT_PROMOTION_NOT_FOUND = "PROMOTION_NOT_FOUND";
	public static final String TEXT_PROMOTION_ID_MUST_BE_NULL = "PROMOTION_ID_MUST_BE_NULL";
	public static final String TEXT_PROMOTION_ESTABLISHMENT_TITLE_IS_ALREADY_IN_USE = "PROMOTION_ESTABLISHMENT_TITLE_IS_ALREADY_IN_USE";
	public static final String TEXT_PROMOTION_MUST_NOT_BE_NULL = "PROMOTION_MUST_NOT_BE_NULL";
	public static final String TEXT_PROMOTION_ESTABLISHMENT_MUST_NOT_BE_NULL = "PROMOTION_ESTABLISHMENT_MUST_NOT_BE_NULL";
	public static final String TEXT_PROMOTION_ESTABLISHMENT_ID_MUST_NOT_BE_NULL = "PROMOTION_ESTABLISHMENT_ID_MUST_NOT_BE_NULL";
	public static final String TEXT_PROMOTION_ESTABLISHMENT_DOES_NOT_EXIST = "PROMOTION_ESTABLISHMENT_DOES_NOT_EXIST";
	public static final String TEXT_PROMOTION_TITLE_MUST_NOT_BE_EMPTY = "PROMOTION_TITLE_MUST_NOT_BE_EMPTY";
	public static final String TEXT_PROMOTION_TITLE_MUST_NOT_BE_BIGGER_THAN_40_CHARACTERS = "PROMOTION_TITLE_MUST_NOT_BE_BIGGER_THAN_40_CHARACTERS";
	public static final String TEXT_PROMOTION_LIMIT_SCORE_MUST_NOT_BE_NULL = "PROMOTION_LIMIT_SCORE_MUST_NOT_BE_NULL";
	public static final String TEXT_PROMOTION_LIMIT_SCORE_MUST_BE_BIGGER_THAN_0 = "PROMOTION_LIMIT_SCORE_MUST_BE_BIGGER_THAN_0";
	public static final String TEXT_PROMOTION_CREATION_MUST_NOT_BE_NULL = "PROMOTION_CREATION_MUST_NOT_BE_NULL";
	public static final String TEXT_PROMOTION_ACTIVE_MUST_NOT_BE_NULL = "PROMOTION_ACTIVE_MUST_NOT_BE_NULL";
	public static final String TEXT_USER_INCORRECT_PASSWORD = "USER_INCORRECT_PASSWORD";
	public static final String TEXT_USER_ID_MUST_BE_NULL = "USER_ID_MUST_BE_NULL";
	public static final String TEXT_USER_NICKNAME_IS_ALREADY_IN_USE = "USER_NICKNAME_IS_ALREADY_IN_USE";
	public static final String TEXT_USER_ID_MUST_NOT_BE_NULL = "USER_ID_MUST_NOT_BE_NULL";
	public static final String TEXT_USER_MUST_NOT_BE_NULL = "USER_MUST_NOT_BE_NULL";
	public static final String TEXT_USER_STATUS_MUST_NOT_BE_NULL = "USER_STATUS_MUST_NOT_BE_NULL";
	public static final String TEXT_USER_STATUS_ID_MUST_NOT_BE_NULL = "USER_STATUS_ID_MUST_NOT_BE_NULL";
	public static final String TEXT_USER_STATUS_DOES_NOT_EXIST = "USER_STATUS_DOES_NOT_EXIST";
	public static final String TEXT_USER_NICKNAME_MUST_NOT_BE_EMPTY = "USER_NICKNAME_MUST_NOT_BE_EMPTY";
	public static final String TEXT_USER_NICKNAME_MUST_NOT_BE_BIGGER_THAN_40_CHARACTERS = "USER_NICKNAME_MUST_NOT_BE_BIGGER_THAN_40_CHARACTERS";
	public static final String TEXT_USER_PASSWORD_MUST_NOT_BE_EMPTY = "USER_PASSWORD_MUST_NOT_BE_EMPTY";
	public static final String TEXT_USER_PASSWORD_MUST_NOT_BE_BIGGER_THAN_128_CHARACTERS = "USER_PASSWORD_MUST_NOT_BE_BIGGER_THAN_128_CHARACTERS";
	public static final String TEXT_USER_ROLE_DOES_NOT_EXIST = "USER_ROLE_DOES_NOT_EXIST";
	
	// model.entity.role
	public static final String TEXT_ROLE_CLIENT = "CLIENT";
	public static final String TEXT_ROLE_ESTABLISHMENT = "ESTABLISHMENT";
	
	// model.entity.status
	public static final String TEXT_STATUS_INACTIVE = "INACTIVE";
	public static final String TEXT_STATUS_ACTIVE = "ACTIVE";
	
	// patterns
	public static final String TEXT_PATTERN_EMAIL = "^[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$";
	
	// http headers
	public static final String TEXT_HEADER_USER_CREDENTIALS = "User-Credentials";
	public static final String TEXT_HEADER_REFERER = "Referer";
	
	// char numbers
	public static final char CHAR_0 = '0';
	public static final char CHAR_1 = '1';
	public static final char CHAR_2 = '2';
	public static final char CHAR_3 = '3';
	public static final char CHAR_4 = '4';
	public static final char CHAR_5 = '5';
	public static final char CHAR_6 = '6';
	public static final char CHAR_7 = '7';
	public static final char CHAR_8 = '8';
	public static final char CHAR_9 = '9';
	
	// content types
	public static final String TEXT_CONTENT_TYPE_IMAGE_JPEG = "IMAGE/JPEG";
	public static final String TEXT_CONTENT_TYPE_IMAGE_JPG = "IMAGE/JPG";
	public static final String TEXT_CONTENT_TYPE_IMAGE_JPE = "IMAGE/JPE";
	public static final String TEXT_CONTENT_TYPE_IMAGE_GIF = "IMAGE/GIF";
	public static final String TEXT_CONTENT_TYPE_IMAGE_PNG = "IMAGE/PNG";
	public static final String TEXT_CONTENT_TYPE_IMAGE_BMP = "IMAGE/BMP";
	
	// charset
	public static final String TEXT_CHARSET_UTF_8 = "UTF-8";
	
	// algorithm
	public static final String TEXT_ALGORITHM_SHA_512 = "SHA-512";
	
	// empty
	public static final String EMPTY = "";
}
